### PR TITLE
Update plugin parent POM and plugin BOM

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
@alecharp Would you be interested in merging/releasing this PR to help with my BOM/PCT efforts?

**Review by alecharp — APPROVED** [review]
We can upgrade BOM later.

**Comment by basil** [comment]
Thanks @alecharp! Are you also interested in doing a release of this?

**Comment by alecharp** [comment]
I can.

**Comment by alecharp** [comment]
and done: https://github.com/jenkinsci/git-server-plugin/releases/tag/git-server-1.11

**Pull request merged**
